BUG: fix critical bug handling files in CWD
Start with an empty dir and place a file in there:
    $ ls
    $ touch foo

Instead of
    $ findsame
    {}

we get
    $ findsame
    Traceback (most recent call last):
        [...]
      File "/path/tofindsame/findsame/calc.py", line 150, in fpr
        fpr = self._get_fpr()
      File "/path/to/findsame/findsame/calc.py", line 191, in _get_fpr
        return self._merge_fpr([c.fpr for c in self.childs])
      File "/path/to/findsame/findsame/calc.py", line 191, in <listcomp>
        return self._merge_fpr([c.fpr for c in self.childs])
      File "/path/to/findsame/findsame/common.py", line 100, in __get__
        value = self.fget(obj)
      File "/path/to/findsame/findsame/calc.py", line 150, in fpr
        fpr = self._get_fpr()
      File "/path/to/findsame/findsame/calc.py", line 191, in _get_fpr
        return self._merge_fpr([c.fpr for c in self.childs])
      File "/path/to/findsame/findsame/calc.py", line 191, in <listcomp>
        return self._merge_fpr([c.fpr for c in self.childs])
    RecursionError: maximum recursion depth exceeded

Reason: os.path.dirname('foo') is '' and we use this as dict key in
FileDirTree, instead of '.' or './'. That case never showed in tests b/c
there we do
    $ findsame /path/to/tests/data
Also in practice we only had the above use case so far ... until now :)